### ISSUE TITLE
Combine sign in and sign up dialog

### ISSUE THREAD

**Issue by sw-yx** [phoqe/rmuif#168]
first of all thanks for this project.

**Is your feature request related to a problem? Please describe.**

i think the current UI of separate signup /singin button is repetitive.

**Describe the solution you'd like**
 i'd like to encourage a combined modal where you can toggle between signup/signin, which overall should be less code.

**Comment by Phoqe** [comment]
I am in favour of this idea, but I am currently uncertain of how that would look. I have some ideas in mind but I’m not sure how to do it in a Material Design fashion just yet. Here are the new authentication dialogs coming with v2.0 if you have an idea on how to implement this, please share!

## SignUpDialog
![localhost_3000_ (1)](https://user-images.githubusercontent.com/7033377/62423929-dcc29e80-b6c7-11e9-83d9-5fd1788e876a.png)

## SignInDialog
![localhost_3000_](https://user-images.githubusercontent.com/7033377/62423930-dd5b3500-b6c7-11e9-826d-e289c321d882.png)

**Comment by sw-yx** [comment]
here's what we do for netlify identity widget: https://identity.netlify.com/

![image](https://user-images.githubusercontent.com/6764957/62439041-3d79c780-b718-11e9-83ce-e9275b35d65e.png)

in general this codebase has a lot of dialogs and therefore requires a lot of boolean states and callbacks to manage the dialogs. it may be possible to get rid of all of them and just have one dialog and a state machine. but ofc that may be more work for you than its worth. i spent a few hours trying to adapt your code for my code style and that was my conclusion.

**Comment by Phoqe** [comment]
The state manager has been improved a lot in v2.0, there is a new `DialogHost` component that holds all the DOM references to the dialogs and will decide when and if they’re going to be displayed. I want to improve it further but it will take some additional research which I don’t have time for at the moment.

I have some ideas on how to do it now in a more Material Design fashion, I will keep this issue updated with design prototypes.

**Comment by sw-yx** [comment]
i understand. thanks for what you have so far!

**Comment by phoqe** [comment]
@sw-yx I will close this as I have new plans for how to proceed with the sign in and sign up flows. I have been working on their separate pages and will provide more of a wizard-like/onboarding experience when signing up and a simple sign in experience.
