### ISSUE TITLE
Add user role managing to the documentation

### ISSUE THREAD

**Issue by ortegoncarlos** [phoqe/rmuif#424]
Hello, thanks for this cool repo,

I think we should add to the documentation some part on how to manage the roles under firebase, and send them to this link https://firebase.google.com/docs/auth/admin/custom-claims?hl=en

Sorry to not pull request

**Comment by ortegoncarlos** [comment]
A little help please, what is the correct way to add the roles

admin.auth().setCustomUserClaims(uid, { appRoles: "admin" }).then(() => {
  // The new custom claims will propagate to the user's ID token the
  // next time a new one is issued.
  console.log("done")
})

**Comment by phoqe** [comment]
Hello @ortegoncarlos, I agree with you that the README is not complete, I am in the process of creating a more complete documentation.

In the meantime, herre’s how you would go about adding roles to a user with a given UID:
```js
const admin = require('firebase-admin');

// export GOOGLE_APPLICATION_CREDENTIALS="/Users/phoqe/Downloads/react-material-ui-firebase-firebase-adminsdk-ected-b81d61fd5e.json"

admin.initializeApp({
  credential: admin.credential.applicationDefault(),
  databaseURL: 'https://react-material-ui-firebase.firebaseio.com'
});

const auth = admin.auth();

setRoles = (uid, roles) => {
  auth.setCustomUserClaims(uid, {
    roles: roles
  }).then((value) => {
    console.log(`${uid}: ${roles}`);
  }).catch((reason) => {
    console.log(reason);
  });
};

setRoles('<YOUR_UID>', [ 'admin', 'premium' ]);
```

**Comment by phoqe** [comment]
@ortegoncarlos There’s now a draft at https://docs.rmuif.com/maintenance/roles
