### ISSUE TITLE
"TypeError: Path must be a string. Received undefined"

### ISSUE THREAD

**Issue by agalanis7** [phoqe/rmuif#432]
When I started the development server I got this:
<img width="1274" alt="Screen Shot 2020-02-14 at 4 11 14 PM" src="https://user-images.githubusercontent.com/30681428/74568050-2a587780-4f45-11ea-87b4-8a094d25a193.png">

**Comment by phoqe** [comment]
I will look into it.

**Comment by phoqe** [comment]
@agalanis7 Can you try checking out the `develop` branch and see if this issue persists?

**Comment by phoqe** [comment]
Appears to be fixed in `master` now. Reopen if it's still happening.
