### ISSUE TITLE
Low PageSpeed Scores

### ISSUE THREAD

**Issue by nainardev** [phoqe/rmuif#434]
Scores very low in mobile

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Frmuif.com%2F&tab=mobile

**Comment by phoqe** [comment]
Thank you, I will look over optimizations in the coming week, although note that this is just a showcase site and not the demo.

**Comment by phoqe** [comment]
Closing as this is no longer relevant as the site will be changed to be more lightweight and more integrated with the docs.
