### ISSUE TITLE
Replace lodash.camelcase

### ISSUE THREAD

**Issue by nainardev** [phoqe/rmuif#440]
@lodash/camelcase is **2.1 kB gzipped** (https://bundlephobia.com/result?p=lodash.camelcase@4.3.0)

Use sindresorhus's [camelcase](https://github.com/sindresorhus/camelcase), which is just **553 B gzipped** (https://bundlephobia.com/result?p=camelcase@5.3.1)

**Comment by phoqe** [comment]
Thank you, this is now fixed in 6869d31ccc8f06a1bf33012dcbf539ffe2502581. :)
