### ISSUE TITLE
[Material-UI] Use top-level imports

### ISSUE THREAD

**Issue by nainardev** [phoqe/rmuif#450]
Results in less bundle size :package: 
Makes statup times faster :rocket: 
```js
#Instead of 
import Button from "@material-ui/core/Button"
import List from "@material-ui/core/List"

#Use 
import { Button, List } from "@material-ui/core"
```

:information_source:Source: https://material-ui.com/guides/minimizing-bundle-size/#option-2

Manually changing each file is not feasible :confused: 
Instead use codemod :robot: 
https://github.com/mui-org/material-ui/blob/master/packages/material-ui-codemod/README.md#top-level-imports
which changes everything for you :smile:

**Comment by phoqe** [comment]
@nainardev You can preview these changes at the [`codemod`](https://github.com/phoqe/rmuif/tree/codemod) branch. I will not roll them out at the moment as I will need some run time before publishing such a change as it change the CRA configuration.
