### ISSUE TITLE
Add admin directory with samples

### ISSUE THREAD

**Issue by phoqe** [phoqe/rmuif#454]

**Comment by nainardev** [comment]
https://gitstalk.netlify.com/phoqe

**Comment by phoqe** [comment]
Here’s a draft for the newly added tools in `/tools`:

There are some maintenance tools at your disposal to help you manage your app easier. These tools include commands for managing users and roles, some are very dangerous to execute, think twice before performing irreversible actions.

It is recommended to read through the entire document before using any tools, especially if your app is in the hands of the public.

## Using an e-mail address instead of a UID

If you don’t know the UID of the user you want to perform operations on, you can use their e-mail address instead. This option will essentially replace all `<uid>` parameters with `<email>`, here’s how you would get the roles of a user using only their e-mail address:

```sh
yarn roles -e get phoqe@phoqe.me
```

:::tip
Anytime the `--email` or `-e` option is present, it will look for an e-mail address instead of a UID.
:::

## user

The `user` tool is used to manage users at an atomic level, e.g. editing the fields of a specific user. You would use this tool if you want to suspend users as well.

### Creating a user

You can use this tool to create new users, e.g. if you wanted to create a test user or system user you can do that. You can initialize more properties from this tool than you can do with the Firebase Console.

The command is as follows, very simple:

```sh
yarn user create
```

This will open a wizard where you insert the new user’s info, like:

```sh
? uid: phoqe
? email: phoqe@phoqe.me
? emailVerified: Yes
? password: password123
? displayName: phoqe
? photoURL:
? disabled: No
┌───────────────┬────────────────┐
│ uid           │ phoqe          │
├───────────────┼────────────────┤
│ email         │ phoqe@phoqe.me │
├───────────────┼────────────────┤
│ emailVerified │ true           │
├───────────────┼────────────────┤
│ password      │ password123    │
├───────────────┼────────────────┤
│ displayName   │ phoqe          │
├───────────────┼────────────────┤
│ photoURL      │ N/A            │
├───────────────┼────────────────┤
│ disabled      │ false          │
└───────────────┴────────────────┘
```

### Getting a user’s data

You can also use this tool to get information about a user, e.g. their display name and whether or not they’re disabled:

```sh
yarn user get <uid>
```

For example, if you would want information about a user with the UID `phoqe`:

```sh
yarn user get phoqe
```

That would yield something like (given that the user exists):

```sh
┌───────────────┬────────────────┐
│ uid           │ phoqe          │
├───────────────┼────────────────┤
│ email         │ phoqe@phoqe.me │
├───────────────┼────────────────┤
│ emailVerified │ true           │
├───────────────┼────────────────┤
│ displayName   │ phoqe          │
├───────────────┼────────────────┤
│ photoURL      │ N/A            │
├───────────────┼────────────────┤
│ disabled      │ false          │
└───────────────┴────────────────┘
```

### Updating a user

Existing users can be modified in almost the same way you create new users. Running this command will prompt you with a wizard filled in with the existing user’s info:

```sh
yarn user update <uid>
```

Updating `phoqe` would look like this:

```sh
yarn user update phoqe
```

And, for the sake of this example, we’ll change the display name to `test`:

```sh
? email: phoqe@phoqe.me
? emailVerified: Yes
? displayName: test
? photoURL:
? disabled: No
┌───────────────┬────────────────┬────────────────┐
│ Key           │ Current Value  │ New Value      │
├───────────────┼────────────────┼────────────────┤
│ email         │ phoqe@phoqe.me │ phoqe@phoqe.me │
├───────────────┼────────────────┼────────────────┤
│ emailVerified │ true           │ true           │
├───────────────┼────────────────┼────────────────┤
│ displayName   │ phoqe          │ test           │
├───────────────┼────────────────┼────────────────┤
│ photoURL      │ N/A            │ N/A            │
├───────────────┼────────────────┼────────────────┤
│ disabled      │ false          │ false          │
└───────────────┴────────────────┴────────────────┘
```

You will then get a prompt asking you whether you want to update the user or not.

### Banning a user

If you want to disable a user, e.g. prevent them from accessing your app, you would do the following with their UID:

```sh
yarn user ban <uid>
```

Let’s say `phoqe` has breached your Terms of Service and you want to suspend his account, you’d run this command:

```sh
yarn user ban phoqe
```

This command is equivalent to setting `disabled` to `true` using the `update` command.

### Unbanning a user

Maybe you don’t want disabled users to stay that way all the time, you can pardon them using:

```sh
yarn user unban <uid>
```

In this case, we’ll unban `phoqe`:

```sh
yarn user unban phoqe
```

### Deleting a user

If banning a user is too light-weight, you can remove them completely;

```sh
yarn user delete <uid>
```

We’ll say goodbye to `phoqe` now:

```sh
yarn user delete phoqe
```

## users

The `users` tool is used to manage users at scale, e.g. deleting all your users or showing many users at once.

### Listing users in a range

You can list users in a specific range using:

```sh
yarn users list <max-results> <next-page-token>
```

For example, getting five users from the fifth page:

```sh
yarn users list 5 5
```

### Deleting all users

This command is very dangerous to use, it will delete all of your users, everyone! Be careful when using it, especially if your app is live.

```sh
yarn users delete
```

As a safety measure, you have to confirm if you want to delete all users.

## roles

The `roles` tool is used to manage roles for users. There are commands for getting, setting, and removing roles from a user.

### Getting a user’s role

In some cases it might be useful to know which roles a user has, you can use this command to find out:

```sh
yarn roles get <uid>
```

If you wanted to get the roles for the user `phoqe`, here’s how you would do it:

```sh
yarn roles get phoqe
```

In this example, `phoqe` now has the `admin` role:

```sh
┌───────┬───────┐
│ roles │ admin │
└───────┴───────┘
```

### Setting a user’s roles

You don’t need to fiddle around with the Firebase Admin SDK everytime you want to change the roles for a user, use this command instead:

```sh
yarn roles set <uid> <roles>
```

Here’s an example of setting the `admin` role for `phoqe`:

```sh
yarn roles set phoqe admin
```

You would get something like this in return:

```sh
┌───────┬───────┐
│ uid   │ phoqe │
├───────┼───────┤
│ roles │ admin │
└───────┴───────┘
```

By the way, the `<roles>` option is comma-separated, meaning you can set multiple roles at once:

```sh
yarn roles set phoqe admin,premium
```

### Removing a user’s roles

Don’t want a user to have any roles? That’s fine, you can remove any user’s role using this command:

```sh
yarn roles remove <uid>
```

This example would remove all the roles associated with the user `phoqe`:

```sh
yarn roles remove phooqe
```

**Comment by nainardev** [comment]
Added to docs?

**Comment by phoqe** [comment]
Yes, it will be a part of the docs under the Tools page.

**Comment by nainardev** [comment]
@phoqe how may I contact you?

**Comment by phoqe** [comment]
I am available on the Discord server and phoqe@phoqe.dev for development related inquiries.
