### ISSUE TITLE
Functional components

### ISSUE THREAD

**Issue by nainardev** [phoqe/rmuif#456]
Atleast begin converting simple components like 404 page, dialog.

**Comment by phoqe** [comment]
You are free to submit a PR converting these components.

**Comment by nainardev** [comment]
Yeah , you got a new contributor :smile:

**Comment by nainardev** [comment]
I'll work on it :zap:

**Comment by tyler-canton** [comment]
I want to contribute :-(

**Comment by nainardev** [comment]
Your contributions are always welcome :blush: . Remember open source is built by community contributions

**Comment by phoqe** [comment]
Yes, @nainardev is right, all contributions are welcome. We will try making contributing easier. Thank you.
