### ISSUE TITLE
Begin using Hooks instead of classes

### ISSUE THREAD

**Issue by phoqe** [phoqe/rmuif#66]
https://reactjs.org/docs/hooks-intro.html

**Comment by sw-yx** [comment]
hi! just wanted to say this would be very welcome. a 1600 line App component is very hard to get into :(

**Comment by Phoqe** [comment]
The App component has been refactored in v2.0 and has been separated into multiple components. You can checkout the `dialog-host` branch.

**Comment by sw-yx** [comment]
👀

**Comment by phoqe** [comment]
Hooks will be used for new components, existing ones will be converted when time comes.
